
export const SET_HEADER_CALLBACK_FORM_SUBMITTED = 'SET_HEADER_CALLBACK_FORM_SUBMITTED';
export type SET_HEADER_CALLBACK_FORM_SUBMITTED = typeof SET_HEADER_CALLBACK_FORM_SUBMITTED;

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export type SELECT_CATEGORY = typeof SELECT_CATEGORY;

export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export type TOGGLE_CATEGORY = typeof TOGGLE_CATEGORY;

export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT';
export type TOGGLE_PRODUCT = typeof TOGGLE_PRODUCT;
