
export const TOGGLE_CALENDAR = 'TOGGLE_CALENDAR';
export type TOGGLE_CALENDAR = typeof TOGGLE_CALENDAR;

export const TOGGLE_TIMERS_SIDEBAR = 'TOGGLE_TIMERS_SIDEBAR';
export type TOGGLE_TIMERS_SIDEBAR = typeof TOGGLE_TIMERS_SIDEBAR;

export const TOGGLE_TASKS_SIDEBAR = 'TOGGLE_TASKS_SIDEBAR';
export type TOGGLE_TASKS_SIDEBAR = typeof TOGGLE_TASKS_SIDEBAR;

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export type OPEN_LOGIN_MODAL = typeof OPEN_LOGIN_MODAL;

export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export type CLOSE_LOGIN_MODAL = typeof CLOSE_LOGIN_MODAL;

export const OPEN_RESET_PASSWORD_MODAL = 'OPEN_RESET_PASSWORD_MODAL';
export type OPEN_RESET_PASSWORD_MODAL = typeof OPEN_RESET_PASSWORD_MODAL;

export const CLOSE_RESET_PASSWORD_MODAL = 'CLOSE_RESET_PASSWORD_MODAL';
export type CLOSE_RESET_PASSWORD_MODAL = typeof CLOSE_RESET_PASSWORD_MODAL;

export const REQUEST_PASSWORD_RESET_EMAIL = 'REQUEST_PASSWORD_RESET_EMAIL';
export type REQUEST_PASSWORD_RESET_EMAIL = typeof REQUEST_PASSWORD_RESET_EMAIL;

export const RESUBMIT_PASSWORD_RESET_REQUEST = 'RESUBMIT_PASSWORD_RESET_REQUEST';
export type RESUBMIT_PASSWORD_RESET_REQUEST = typeof RESUBMIT_PASSWORD_RESET_REQUEST;

export const RESET_PASSWORD = 'RESET_PASSWORD';
export type RESET_PASSWORD = typeof RESET_PASSWORD;