

export const INCREMENT_CART_ITEM = 'INCREMENT_CART_ITEM';
export type INCREMENT_CART_ITEM = typeof INCREMENT_CART_ITEM;

export const DECREMENT_CART_ITEM = 'DECREMENT_CART_ITEM';
export type DECREMENT_CART_ITEM = typeof DECREMENT_CART_ITEM;

export const SET_CART_ITEM_AMOUNT = 'SET_CART_ITEM_AMOUNT';
export type SET_CART_ITEM_AMOUNT = typeof SET_CART_ITEM_AMOUNT;

export const LOAD_CART_PRODUCTS = 'LOAD_CART_PRODUCTS';
export type LOAD_CART_PRODUCTS = typeof LOAD_CART_PRODUCTS;

