

export const ADD_TASKS = 'ADD_TASKS';
export type ADD_TASKS = typeof ADD_TASKS;

export const REMOVE_TASKS = 'REMOVE_TASKS';
export type REMOVE_TASKS = typeof REMOVE_TASKS;

export const ADD_TASK_LABELS = 'ADD_TASK_LABELS';
export type ADD_TASK_LABELS = typeof ADD_TASK_LABELS;

export const REMOVE_TASK_LABELS = 'REMOVE_TASK_LABELS';
export type REMOVE_TASK_LABELS = typeof REMOVE_TASK_LABELS;

export const ADD_TASK_INTERVALS = 'ADD_TASK_INTERVALS';
export type ADD_TASK_INTERVALS = typeof ADD_TASK_INTERVALS;

export const REMOVE_TASK_INTERVALS = 'REMOVE_TASK_INTERVALS';
export type REMOVE_TASK_INTERVALS = typeof REMOVE_TASK_INTERVALS;

export const ADD_TASK_BOARD_LISTS = 'ADD_TASK_BOARD_LISTS';
export type ADD_TASK_BOARD_LISTS = typeof ADD_TASK_BOARD_LISTS;

export const REMOVE_TASK_BOARD_LISTS = 'REMOVE_TASK_BOARD_LISTS';
export type REMOVE_TASK_BOARD_LISTS = typeof REMOVE_TASK_BOARD_LISTS;
