import { library } from '@fortawesome/fontawesome-svg-core';

import {
    faBuilding,
    faUsers,
    faFileAlt,
    faFile,
    faSortNumericDown,
    faMoneyBill,
    faTruck,
    faEnvelope,
    faPhone,
    faSpinner,
    faSearch,
    faCaretDown,
    faCaretUp,
    faChevronDown,
    faChevronUp,
    faPrint,
    faTimes,
    faGlobeAmericas,
    faUser,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faTimes,
    faBuilding,
    faUsers,
    faFileAlt,
    faPrint,
    faSortNumericDown,
    faMoneyBill,
    faTruck,
    faEnvelope,
    faPhone,
    faSpinner,
    faSearch,
    faCaretDown,
    faCaretUp,
    faChevronDown,
    faChevronUp,
    faGlobeAmericas,
    faUser,
);
