
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export type LOAD_PRODUCTS = typeof LOAD_PRODUCTS;

export const LOAD_FILTERING_ATTRIBUTES = 'LOAD_FILTERING_ATTRIBUTES';
export type LOAD_FILTERING_ATTRIBUTES = typeof LOAD_FILTERING_ATTRIBUTES;

export const IMAGES_PATH_URL = 'http://78.155.206.50/media/images/';
export type IMAGES_PATH_URL = typeof IMAGES_PATH_URL;
